source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

project 'CocoapodsLibrary.xcodeproj'

target 'CocoapodsLibrary'  do

pod 'AFNetworking'
pod 'ZCEasyLibrary'

end

